// Tipo de dado: String
//const nome = "Eduarda";
//Tipo de dado: Number
//const idade = 19;
//Tipo de dado: Boolean
//let fazFaculdade = true;

//console.log("Eduarda faz faculdade?", fazFaculdade);
//console.log("Alguns anos depois...")

//fazFaculdade = false;
//console.log("Eduarda faz faculdade?", fazFaculdade);

//Tipo de dado: Undefined
//let profissao;
//console.log(profissao);

//profissao = "Programadora";
//console.log(profissao);

//let carro = null;
//console.log("Eduarda tem carro?", carro);